#!/bin/bash

OUTPUT_DIR="/home/wolfee182/rips/completed/"
SOURCE_DRIVE="/dev/sr0"
HANDBRAKE_PRESET="AppleTV 3"
EXTENSION="mkv"

function rip_bluray() {

        # Grab the DVD title
        BLURAY_TITLE=$(blkid -o value -s LABEL $SOURCE_DRIVE)
        # Replace spaces with underscores
        BLURAY_TITLE=${BLURAY_TITLE// /_}

        # Backup the DVD to out hard drive
        makemkvcon backup disc:0 $OUTPUT_DIR/$BLURAY_TITLE --decrypt

        # grep for the HandBrakeCLI process and get the PID
        HANDBRAKE_PID=`ps aux|grep H\[a\]ndBrakeCLI`
        set -- $HANDBRAKE_PID
        HANDBRAKE_PID=$2

        # Wait until our previous Handbrake job is done
        if [ -n "$HANDBRAKE_PID" ]
        then
                while [ -e /proc/$HANDBRAKE_PID ]; do sleep 1; done
        fi

        # HandBrake isn't ripping anything so we can pop out the disc
        eject $SOURCE_DRIVE

        # And now we can start encoding
        HandBrakeCLI -i $OUTPUT_DIR/$BLURAY_TITLE -o $OUTPUT_DIR/$BLURAY_TITLE.$EXTENSION --preset=$HANDBRAKE_PRESET

        # Clean up
        rm -R $OUTPUT_DIR/$BLURAY_TITLE
}

rip_bluray

#rsync --remove-source-files -zvhr /home/wolfee182/rips/completed/* 192.168.1.60:/media/wolfee182/Data/Media/Movies/Unsorted
#rmdir /home/wolfee182/rips/completed/*
